apiVersion: inventory.open-cluster-management.io/v1alpha1
kind: BareMetalAsset
metadata:
  name: ginkgo-master-3
spec:
  bmc:
    address: ipmi://192.100.100.14
    credentialsName: dc01r3c3b2-powerflex390-bmc-secret
  bootMACAddress: "52:10:11:12:13:18"
